### ISSUE TITLE
Prometheus 添加监控目标

### ISSUE THREAD

**Issue by kehao95** [kehao95/Blog#4]
添加固定目标

``` yaml
scrape_configs:
  - job_name: 'Monitoring'
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'localhost:9090'
```

**Comment by kehao95** [comment]
修改scrap job的参数

```yaml
  - job_name: 'netdata-scrape'
    # How frequently to scrape targets from this job.
    [ scrape_interval: <duration> | default = <global_config.scrape_interval> ]
    # Per-scrape timeout when scraping this job.
    [ scrape_timeout: <duration> | default = <global_config.scrape_timeout> ]
    # The HTTP resource path on which to fetch metrics from targets.
    [ metrics_path: <path> | default = /metrics ]
    [ honor_labels: <boolean> | default = false ]
    # Configures the protocol scheme used for requests.
    [ scheme: <scheme> | default = http ]
    # Optional HTTP URL parameters.
    params:
    [ <string>: [<string>, ...] ]
    # Sets the `Authorization` header on every scrape request
    basic_auth:
    [ username: <string> ]
    [ password: <secret> ]
    static_configs:
      - targets: ['{your.netdata.ip}:19999']
```
以netdata Prometheus API为例：

``` yaml
  - job_name: 'netdata-scrape'

    metrics_path: '/api/v1/allmetrics'
    params:
      # format: prometheus | prometheus_all_hosts
      format: [prometheus]
      # source: as-collected | raw | average | sum | volume
      #source: [as-collected]
      # server name for this prometheus - the default is the client IP
      #server: prometheus1
    honor_labels: true

    static_configs:
      - targets: ['{your.netdata.ip}:19999']
```
