### ISSUE TITLE
Ansible 入门

### ISSUE THREAD

**Issue by kehao95** [kehao95/Blog#5]

**Comment by kehao95** [comment]
## Ansible 安装
`pip install ansible`

## Ansible 配置文件
ansible的默认配置文件是/etc/ansible/ansible.cfg。其实ansible会按照下面的顺序查找配置文件，并使用第一个发现的配置文件。
* ANSIBLE_CONFIG (an environment variable)
* ansible.cfg (in the current directory)
* .ansible.cfg (in the home directory)
* /etc/ansible/ansible.cfg

基本配置`ansible.cfg`
```
inventory      = /etc/ansible/hosts
library        = /usr/share/my_modules/
remote_tmp     = $HOME/.ansible/tmp
local_tmp      = $HOME/.ansible/tmp
```
[高级配置范例](https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg)

## 主机清单(Host inventory)
主机清单定义在 inventory file中：`inventory  = /etc/ansible/hosts`
格式如下
```
[group{:subgroup}]
host1     {para1=value1 para2=value2}
host2
[group:vars]
var1=value1
```
例：

```
mail.example.com

[webservers]
foo.example.com
bar.example.com

[southeast:children]
atlanta
raleigh


[targets]
localhost              ansible_connection=local
other1.example.com     ansible_connection=ssh        ansible_user=mpdehaan

[atlanta:vars]
ntp_server=ntp.atlanta.example.com
proxy=proxy.atlanta.example.com
```

**Comment by kehao95** [comment]
## Ansible Playbook 构成
ansible playbook 是yaml格式文件，完整的Ansible Playbook包含三部分：
1. 在什么机器上以什么身份执行
  * hosts
  * users
  * …
2. 执行的任务是都有什么
  * tasks
3. 善后的任务都有什么
  * handlers
示例：
```yaml
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  user: root
  tasks:
  - name: ensure apache is at the latest version
    yum: pkg=httpd state=latest
  - name: write the apache config file
    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service: name=httpd state=started
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
```
